// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnisphiaWynnPalettia(arg1, arg2) {
  return window['go']['main']['App']['AnisphiaWynnPalettia'](arg1, arg2);
}

export function ClaireFrancois(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ClaireFrancois'](arg1, arg2, arg3, arg4, arg5);
}

export function HimeShiraki() {
  return window['go']['main']['App']['HimeShiraki']();
}

export function HougetsuShimamura() {
  return window['go']['main']['App']['HougetsuShimamura']();
}

export function KanadeAmou(arg1) {
  return window['go']['main']['App']['KanadeAmou'](arg1);
}

export function KanokoMamiya(arg1) {
  return window['go']['main']['App']['KanokoMamiya'](arg1);
}

export function MahiruKozuki(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MahiruKozuki'](arg1, arg2, arg3, arg4, arg5);
}

export function MitsukiYano() {
  return window['go']['main']['App']['MitsukiYano']();
}

export function MiyakoKodama(arg1, arg2) {
  return window['go']['main']['App']['MiyakoKodama'](arg1, arg2);
}

export function NagisaKiryu(arg1, arg2) {
  return window['go']['main']['App']['NagisaKiryu'](arg1, arg2);
}

export function NodokaManabe(arg1) {
  return window['go']['main']['App']['NodokaManabe'](arg1);
}

export function RaeTaylor(arg1, arg2) {
  return window['go']['main']['App']['RaeTaylor'](arg1, arg2);
}

export function SakuraAdachi(arg1) {
  return window['go']['main']['App']['SakuraAdachi'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function SumikaTachibana(arg1) {
  return window['go']['main']['App']['SumikaTachibana'](arg1);
}

export function TamaoSuzumi() {
  return window['go']['main']['App']['TamaoSuzumi']();
}

export function Tarumi() {
  return window['go']['main']['App']['Tarumi']();
}

export function TiltyClaret() {
  return window['go']['main']['App']['TiltyClaret']();
}

export function Tohru(arg1) {
  return window['go']['main']['App']['Tohru'](arg1);
}

export function TomoriShikina(arg1) {
  return window['go']['main']['App']['TomoriShikina'](arg1);
}

export function UiHirasawa(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UiHirasawa'](arg1, arg2, arg3, arg4);
}

export function YayaNanto() {
  return window['go']['main']['App']['YayaNanto']();
}

export function YuuKoito(arg1) {
  return window['go']['main']['App']['YuuKoito'](arg1);
}
