// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';
import {world} from '../models';

export function AnisphiaWynnPalettia(arg1:string,arg2:string):Promise<Array<main.SearchHit>>;

export function ClaireFrancois(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:string):Promise<main.AppError>;

export function HimeShiraki():Promise<main.SceneView>;

export function HougetsuShimamura():Promise<string>;

export function KanadeAmou(arg1:string):Promise<main.AppError>;

export function KanokoMamiya(arg1:string):Promise<main.AppError>;

export function MahiruKozuki(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:string):Promise<main.AppError>;

export function MitsukiYano():Promise<Array<main.EntryView>>;

export function MiyakoKodama(arg1:string,arg2:number):Promise<Array<main.SearchHit>>;

export function NagisaKiryu(arg1:string,arg2:string):Promise<main.ModelListResult>;

export function NodokaManabe(arg1:string):Promise<main.ImportResult>;

export function RaeTaylor(arg1:string,arg2:main.EntryPatch):Promise<main.AppError>;

export function SakuraAdachi(arg1:number):Promise<Array<main.EventView>>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function SumikaTachibana(arg1:world.WorldManifest):Promise<main.AppError>;

export function TamaoSuzumi():Promise<Array<main.WorldInfo>>;

export function Tarumi():Promise<main.AppError>;

export function TiltyClaret():Promise<Array<main.EntryView>>;

export function Tohru(arg1:string):Promise<main.AppError>;

export function TomoriShikina(arg1:string):Promise<main.AppError>;

export function UiHirasawa(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<main.AppError>;

export function YayaNanto():Promise<world.WorldManifest>;

export function YuuKoito(arg1:string):Promise<main.EntryView>;
